### ISSUE TITLE
[Add more data structures and algorithms in C++]

### ISSUE THREAD

**Issue by ShehrozIrfan** [ShehrozIrfan/learn-dsa#15]
We need to add more data structures and algorithms in C++. Think of a concept that is already not in our C++ folders, and add that. Like you can think of adding:
- Pointers
- More interview-related questions
- Make improvements to the existing code 
- Improving the documentation

### Guidelines

-  Please make sure you are using the right folder structure for your contribution like we've used for `C++`, like  [here](https://github.com/ShehrozIrfan/learn-dsa/tree/master/C%2B%2B)

- Please visit [CONTRIBUTING.md](https://github.com/ShehrozIrfan/learn-dsa/blob/master/CONTRIBUTING.md) for contributions.

- Whatever program you add, ensure you're adding the relevant comments, and it is easier to understand what the code does and the main concept.

**Comment by SamantaTarun** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by ShehrozIrfan** [comment]
Hey @tarunsamanta2k20 
I'm glad to hear that you want to contribute.

Please create an issue, with the description of the changes you want to add.

Thanks.

**Comment by SamantaTarun** [comment]
I added some bit manipulations fundamental questions with answers. Created
a PR as well. Please review and merge them.

**Comment by SikandarJODD** [comment]
I want to Work on this Issue by Adding Sliding Window and Stack and Hashing in Cpp, i have solved may DSA Question on Leetcode, Codeforces, and Codechef

**Comment by ShehrozIrfan** [comment]
> I want to Work on this Issue by Adding Sliding Window and Stack and Hashing in Cpp, i have solved may DSA Question on Leetcode, Codeforces, and Codechef

Hey @SikandarJODD 
I'm glad to hear that you've solved DSA questions on multiple platforms, you can contribute to this repo by opening a PR with the changes you want to add.

Have fun!

**Comment by bascum** [comment]
I have an algorithm for a weighted random number generator. I would love to add it if you feel it would fit your project
